version: 2
updates:
- package-ecosystem: npm
  target-branch: 'master'
  directory: "/sbt-plugin/src/node"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: npm
  target-branch: 'demo/akka-idtlt'
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: npm
  target-branch: 'demo/akka-http-svlete'
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
