// Generated by ScalaTS 0.5.8-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Transport, isTransport } from './Transport';

export interface BusLine extends Transport {
  id: number;
  name: string;
  stopIds: ReadonlyArray<string>;
}

export function isBusLine(v: any): v is BusLine {
  return (
    (Array.isArray(v['stopIds']) && v['stopIds'].every(elmt => (typeof elmt) === 'string')) &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['id']) === 'number')
  );
}
