// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsCaseClassBar = exports;

export interface CaseClassBar {
  firstName: string;
  lastName: string;
}

export function isCaseClassBar(v: any): v is CaseClassBar {
  return (
    ((typeof v['firstName']) === 'string') &&
    ((typeof v['lastName']) === 'string')
  );
}
