// Generated by ScalaTS 0.5.10-SNAPSHOT: https://scala-ts.github.io/scala-ts/

export interface CaseClassBar {
  firstName: string;
  lastName: string;
}

export function isCaseClassBar(v: any): v is CaseClassBar {
  return (
    ((typeof v['firstName']) === 'string') &&
    ((typeof v['lastName']) === 'string')
  );
}
