// Generated by ScalaTS 0.5.9-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { NamedFeature, isNamedFeature } from './NamedFeature';
import { Transport, isTransport } from './Transport';

export interface TrainLine extends Transport {
  name: string;
  startStationId: string;
  endStationId: string;
  feature: NamedFeature;
}

export function isTrainLine(v: any): v is TrainLine {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['startStationId']) === 'string') &&
    ((typeof v['endStationId']) === 'string') &&
    (v['feature'] && isNamedFeature(v['feature']))
  );
}
