// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Alabama
export const idtltAlabama = idtlt.literal("AL");

// Super-type declaration State is ignored

// Deriving TypeScript type from Alabama validator
export type Alabama = typeof idtltAlabama.T;
