// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { Transport } from './Transport';

// Validator for InterfaceDeclaration Bar
export const idtltBar = idtlt.object({
  created: idtlt.isoDate,
  updated: idtlt.isoDate,
  transports: idtlt.array(idtltTransport),
  amount: idtlt.number,
  age: idtlt.number,
  name: idtlt.string,
});

// Deriving TypeScript type from Bar validator
export type Bar = typeof idtltBar.T;
