// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { Transport } from './Transport';

// Validator for InterfaceDeclaration Foo
export const idtltFoo = idtlt.object({
  row: idtlt.tuple(idtlt.string, idtltTransport, idtlt.isoDate),
  namespace: idtlt.tuple(idtlt.number, idtlt.string),
  id: idtlt.number,
});

// Deriving TypeScript type from Foo validator
export type Foo = typeof idtltFoo.T;
