// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { Whatever } from './Whatever';
import { Hi } from './Hi';
import { Bye } from './Bye';
import { Hello } from './Hello';
import { GoodBye } from './GoodBye';

// Validator for UnionDeclaration Greeting
export const idtltGreeting = idtlt.discriminatedUnion(
  '_type',
  idtltBye,
  idtltGoodBye,
  idtltHello,
  idtltHi,
  idtltWhatever);

// Deriving TypeScript type from Greeting validator
export type Greeting = typeof idtltGreeting.T;
