// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Hello
export const idtltHello = idtlt.literal('Hello')

// Super-type declaration Greeting is ignored

// Deriving TypeScript type from Hello validator
export type Hello = typeof idtltHello.T;
