// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { NotSupportedClassAsTypeArgs } from './NotSupportedClassAsTypeArgs';

// Validator for InterfaceDeclaration NotSupportedAsNotSupportedField
export const idtltNotSupportedAsNotSupportedField = idtlt.object({
  notSupportedClassAsTypeArgs: idtlt.unknown /* Unsupported 'NotSupportedClassAsTypeArgs'; Type parameters: idtlt.number */,
});

// Deriving TypeScript type from NotSupportedAsNotSupportedField validator
export type NotSupportedAsNotSupportedField = typeof idtltNotSupportedAsNotSupportedField.T;
