// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { Alabama } from './Alabama';
import { Alaska } from './Alaska';

// Validator for UnionDeclaration State
export const idtltState = idtlt.discriminatedUnion(
  '_type',
  idtltAlabama,
  idtltAlaska);

// Deriving TypeScript type from State validator
export type State = typeof idtltState.T;
