// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for InterfaceDeclaration TrainLine
export const idtltTrainLine = idtlt.object({
  endStationId: idtlt.string,
  startStationId: idtlt.string,
  name: idtlt.string,
});

// Super-type declaration Transport is ignored

// Deriving TypeScript type from TrainLine validator
export type TrainLine = typeof idtltTrainLine.T;
