// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import { TrainLine } from './TrainLine';
import { BusLine } from './BusLine';

// Validator for UnionDeclaration Transport
export const idtltTransport = idtlt.discriminatedUnion(
  '_type', idtltBusLine, idtltTrainLine);

// Fields are ignored: name

// Deriving TypeScript type from Transport validator
export type Transport = typeof idtltTransport.T;
