// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for EnumDeclaration WeekDay
export const idtltWeekDay = idtlt.union(
  idtlt.literal('Mon'),
  idtlt.literal('Tue'),
  idtlt.literal('Wed'),
  idtlt.literal('Thu'),
  idtlt.literal('Fri'),
  idtlt.literal('Sat'),
  idtlt.literal('Sun'))

export const idtltDiscriminatedWeekDay = idtlt.intersection(
  idtltWeekDay,
  idtlt.object({
    '_type': idtlt.literal('WeekDay')
  })
);

// Deriving TypeScript type from WeekDay validator
export type WeekDay = typeof idtltWeekDay.T;
