// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for InterfaceDeclaration Whatever
export const idtltWhatever = idtlt.object({
  word: idtlt.string,
});

// Super-type declaration Greeting is ignored

// Deriving TypeScript type from Whatever validator
export type Whatever = typeof idtltWhatever.T;
