// Generated by ScalaTS 0.5.6: https://scala-ts.github.io/scala-ts/

import type { Feature } from './Feature';

export class Bar implements Feature {
  private static instance: Bar;

  private constructor() {}

  public static getInstance() {
    if (!Bar.instance) {
      Bar.instance = new Bar();
    }

    return Bar.instance;
  }
}
