// Generated by ScalaTS 0.8.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsBusLine = exports;

import * as nsTransport from './Transport';
import type { Transport } from './Transport';

export const dependencyModules = [
  nsTransport,
];

export interface BusLine extends Transport {
  id: number;
  name: string;
  stopIds: ReadonlyArray<string>;
}

export function isBusLine(v: any): v is BusLine {
  return (
    ((typeof v['id']) === 'number') &&
    ((typeof v['name']) === 'string') &&
    (Array.isArray(v['stopIds']) && v['stopIds'].every(elmt => (typeof elmt) === 'string'))
  );
}
