// Generated by ScalaTS 0.8.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsCaseClassBar = exports;

import * as nsGrade from './Grade';
import type { Grade } from './Grade';

export const dependencyModules = [
  nsGrade,
];

export interface CaseClassBar {
  firstName: string;
  lastName: string;
  grade: Grade;
  time: string;
}

export function isCaseClassBar(v: any): v is CaseClassBar {
  return (
    ((typeof v['firstName']) === 'string') &&
    ((typeof v['lastName']) === 'string') &&
    (v['grade'] && nsGrade.isGrade(v['grade'])) &&
    ((typeof v['time']) === 'string')
  );
}
