// Generated by ScalaTS 0.7.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsCaseClassFoo = exports;

import * as nsCaseClassBar from './CaseClassBar';
import type { CaseClassBar } from './CaseClassBar';

export const dependencyModules = [
  nsCaseClassBar,
];

export interface CaseClassFoo {
  id: string;
  name: string;
  i: number;
  flag: number;
  score: number;
  time: number;
  localDate: Date;
  instant: Date;
  localDateTime: Date;
  offsetDateTime: Date;
  zonedDateTime: Date;
  ts: Date;
  tuple2: [string, number];
  tuple3: [Date, Date, CaseClassFoo];
  bar?: CaseClassBar;
}

export function isCaseClassFoo(v: any): v is CaseClassFoo {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['i']) === 'number') &&
    ((typeof v['flag']) === 'number') &&
    ((typeof v['score']) === 'number') &&
    ((typeof v['time']) === 'number') &&
    (v['localDate'] && (v['localDate'] instanceof Date)) &&
    (v['instant'] && (v['instant'] instanceof Date)) &&
    (v['localDateTime'] && (v['localDateTime'] instanceof Date)) &&
    (v['offsetDateTime'] && (v['offsetDateTime'] instanceof Date)) &&
    (v['zonedDateTime'] && (v['zonedDateTime'] instanceof Date)) &&
    (v['ts'] && (v['ts'] instanceof Date)) &&
    (Array.isArray(v['tuple2']) && v['tuple2'].length == 2 && ((typeof v['tuple2'][0]) === 'string') && ((typeof v['tuple2'][1]) === 'number')) &&
    (Array.isArray(v['tuple3']) && v['tuple3'].length == 3 && (v['tuple3'][0] && (v['tuple3'][0] instanceof Date)) && (v['tuple3'][1] && (v['tuple3'][1] instanceof Date)) && (v['tuple3'][2] && nsCaseClassFoo.isCaseClassFoo(v['tuple3'][2]))) &&
    (!v['bar'] || (v['bar'] && nsCaseClassBar.isCaseClassBar(v['bar'])))
  );
}
