// Generated by ScalaTS 0.5.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { CaseClassBar } from './CaseClassBar';

export interface CaseClassFoo {
  id: string;
  name: string;
  i: number;
  flag: number;
  score: number;
  time: number;
  localDate: Date;
  instant: Date;
  localDateTime: Date;
  offsetDateTime: Date;
  zonedDateTime: Date;
  ts: Date;
  tuple2: [string, number];
  tuple3: [Date, Date, CaseClassFoo];
  bar?: CaseClassBar;
}
