// Generated by ScalaTS 0.5.8-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Grade, isGrade } from './Grade';

export interface CaseClassBar {
  firstName: string;
  lastName: string;
  grade: Grade;
}

export function isCaseClassBar(v: any): v is CaseClassBar {
  return (
    (v['grade'] && isGrade(v['grade'])) &&
    ((typeof v['lastName']) === 'string') &&
    ((typeof v['firstName']) === 'string')
  );
}
