// Generated by ScalaTS 0.5.12-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsFeature = exports;

export interface Feature {
}

export function isFeature(v: any): v is Feature {
  return (
    v === {}
  );
}
