// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsGrade = exports;

export type Grade = number;

export function isGrade(v: any): v is Grade {
  return (typeof v) === 'number';
}
