// Generated by ScalaTS 0.5.6: https://scala-ts.github.io/scala-ts/

import type { Category } from './Category';

export class Ipsum implements Category {
  private static instance: Ipsum;

  private constructor() {}

  public static getInstance() {
    if (!Ipsum.instance) {
      Ipsum.instance = new Ipsum();
    }

    return Ipsum.instance;
  }
}
