// Generated by ScalaTS 0.5.6: https://scala-ts.github.io/scala-ts/

import type { Category } from './Category';

export class Lorem implements Category {
  private static instance: Lorem;

  private constructor() {}

  public static getInstance() {
    if (!Lorem.instance) {
      Lorem.instance = new Lorem();
    }

    return Lorem.instance;
  }
}
