// Generated by ScalaTS 0.5.9-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Category, isCategory } from './Category';

export class Lorem implements Category {
  private static instance: Lorem;

  private constructor() {}

  public static getInstance() {
    if (!Lorem.instance) {
      Lorem.instance = new Lorem();
    }

    return Lorem.instance;
  }
}

export function isLorem(v: any): v is Lorem {
  return (v instanceof Lorem) && (v === Lorem.getInstance());
}
