// Generated by ScalaTS 0.5.12-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import * as nsFeature from './Feature';
import { Feature, isFeature } from './Feature';

export interface NamedFeature {
  name: string;
  feature: Feature;
}

export function isNamedFeature(v: any): v is NamedFeature {
  return (
    ((typeof v['name']) === 'string') &&
    (v['feature'] && isFeature(v['feature']))
  );
}
