// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Transport } from './Transport';

export interface TrainLine extends Transport {
  name: string;
  startStationId: string;
  endStationId: string;
}
