// Generated by ScalaTS 0.5.8-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Transport, isTransport } from './Transport';

export interface TrainLine extends Transport {
  name: string;
  startStationId: string;
  endStationId: string;
}

export function isTrainLine(v: any): v is TrainLine {
  return (
    ((typeof v['endStationId']) === 'string') &&
    ((typeof v['startStationId']) === 'string') &&
    ((typeof v['name']) === 'string')
  );
}
