@startuml
skinparam sequence {
  ActorBorderColor #000
  LifeLineBorderColor #000
  ParticipantBorderColor #000
  ParticipantFontColor #fff
  ActorBackgroundColor #fff
}

actor User
participant "UI\n(TypeScript/Svelte)" as UI #007acc
participant "REST API\n(Scala/Akka-HTTP)" as API #dd3633

User -> UI : Signup using
activate UI #007acc
UI -> API : POST /signup (Account)
activate API #dd3633
UI <- API : Ok(UserName) | error
deactivate API
deactivate UI

User -> UI : Login
activate UI #007acc

UI -> API : POST /signin (Credentials)
activate API #dd3633
UI <- API : Ok(UserToken) | error
deactivate API

UI -> UI : [If Ok] Redirect to profile
activate UI #229cee
UI -> API : GET
activate API #dd3633
UI <- API : Account
deactivate API
deactivate UI

deactivate UI
@enduml
