# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import name  # noqa: F401
from name import Name
import transport  # noqa: F401
from transport import Transport


# Declare interface Bar
@dataclass
class Bar:
    name: Name
    aliases: typing.List[Name]
    age: int
    amount: typing.Optional[complex]
    transports: typing.List[Transport]
    updated: datetime.datetime
    created: datetime.datetime
