# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import name  # Name
import transport  # Transport


# Declare interface Bar
@dataclass
class Bar:
    name: name.Name
    aliases: typing.List[name.Name]
    age: int
    amount: typing.Optional[complex]
    transports: typing.List[transport.Transport]
    updated: datetime.datetime
    created: datetime.datetime
