# Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401


# Declare interface BusLine
@dataclass
class BusLine:
    id: int
    name: str
    stopIds: typing.List[str]
