# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import transport  # Transport


# Declare interface BusLine
@dataclass
class BusLine(transport.Transport):
    id: int
    name: str
    stopIds: typing.List[str]
