# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import ipsum  # noqa: F401
from ipsum import Ipsum
import lorem  # noqa: F401
from lorem import Lorem


# Declare union Category
Category = typing.Union[Ipsum, Lorem]


class CategoryCompanion:
    @classmethod
    def Ipsum(self) -> Category:
        return ipsum.IpsumInhabitant

    @classmethod
    def Lorem(self) -> Category:
        return lorem.LoremInhabitant
