# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import ipsum  # Ipsum
import lorem  # Lorem


# Declare union Category
Category = typing.Union[ipsum.Ipsum, lorem.Lorem]
