# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import classwithtypeargs  # noqa: F401
from classwithtypeargs import ClassWithTypeArgs


# Declare interface ClassWithGenericField
@dataclass
class ClassWithGenericField:
    notSupportedClassAsTypeArgs: ClassWithTypeArgs[float]
