# Generated by ScalaTS 0.8.1: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass  # noqa: F401
import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401

from generated import httperrors  # Singleton


# Declare singleton Faults
class FaultsInvariantsFactory:
    @classmethod
    def http(self) -> typing.List[str]:
        return [httperrors.HttpErrorsInvariantsFactory.NotFound(), httperrors.HttpErrorsInvariantsFactory.InternalServerError()]


@dataclass
class IFaultsInvariants:
    http: typing.List[str]


FaultsInvariants = IFaultsInvariants(
    http=FaultsInvariantsFactory.http(),
)
