# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import barnum  # noqa: F401
from barnum import BarNum
import foolure  # noqa: F401
from foolure import FooLure


# Declare union Feature
Feature = typing.Union[BarNum, FooLure]


class FeatureCompanion:
    @classmethod
    def BarNum(self) -> Feature:
        return barnum.BarNumInhabitant

    @classmethod
    def FooLure(self) -> Feature:
        return foolure.FooLureInhabitant
