# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import barnum  # BarNum
import foolure  # FooLure


# Declare union Feature
Feature = typing.Union[barnum.BarNum, foolure.FooLure]
