# Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass  # noqa: F401
import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401


# Declare singleton GoodBye
GoodBye = typing.Literal['GoodBye']
GoodByeInhabitant: GoodBye = 'GoodBye'
