# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import bye  # Bye
import goodbye  # GoodBye
import hello  # Hello
import hi  # Hi
import whatever  # Whatever


# Declare union Greeting
Greeting = typing.Union[typing.Union[typing.Union[typing.Union[bye.Bye, goodbye.GoodBye], hello.Hello], hi.Hi], whatever.Whatever]
