# Generated by ScalaTS 0.8.0: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass  # noqa: F401
import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401


# Declare singleton Hi
Hi = typing.Literal['Hi']
HiInhabitant: Hi = 'Hi'
