# Generated by ScalaTS 0.8.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass  # noqa: F401
import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401


# Declare singleton Ipsum
Ipsum = typing.Literal['Ipsum']
IpsumInhabitant: Ipsum = 'Ipsum'
