# Generated by ScalaTS 0.8.0: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401


# Declare tagged type Name
Name = typing.NewType('Name', str)
