# Generated by ScalaTS 0.5.18: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401
import time  # noqa: F401

from generated import alabama  # noqa: F401
from generated.alabama import Alabama
from generated import alaska  # noqa: F401
from generated.alaska import Alaska


# Declare union State
State = typing.Union[Alabama, Alaska]


class StateCompanion:
    @classmethod
    def Alabama(self) -> State:
        return alabama.AlabamaInhabitant

    @classmethod
    def Alaska(self) -> State:
        return alaska.AlaskaInhabitant


StateKnownValues: typing.List[State] = [
    StateCompanion.Alabama(),
    StateCompanion.Alaska(),
]
