# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import alabama  # noqa: F401
from alabama import Alabama
import alaska  # noqa: F401
from alaska import Alaska


# Declare union State
State = typing.Union[Alabama, Alaska]


class StateCompanion:
    @classmethod
    def Alabama(self) -> State:
        return alabama.AlabamaInhabitant

    @classmethod
    def Alaska(self) -> State:
        return alaska.AlaskaInhabitant
