# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import transport  # Transport


# Declare interface TrainLine
@dataclass
class TrainLine(transport.Transport):
    name: str
    startStationId: str
    endStationId: str
