# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import busline  # noqa: F401
from busline import BusLine
import trainline  # noqa: F401
from trainline import TrainLine


# Declare union Transport
Transport = typing.Union[BusLine, TrainLine]

# Fields are ignored: name
