# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import busline  # BusLine
import trainline  # TrainLine


# Declare union Transport
Transport = typing.Union[busline.BusLine, trainline.TrainLine]

# Fields are ignored: name
