# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

from dataclasses import dataclass
import typing  # noqa: F401
import datetime  # noqa: F401

import greeting  # Greeting


# Declare interface Whatever
@dataclass
class Whatever(greeting.Greeting):
    word: str
