# Generated by ScalaTS 0.5.14-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import typing  # noqa: F401
import datetime  # noqa: F401

import greeting  # Greeting


# Declare singleton Words
class WordsInvariants:
    @classmethod
    def start(self) -> typing.List[greeting.Greeting]:
        return [greeting.Greeting.Hello(), greeting.Greeting.Hi()]


WordsInhabitant = {
    'start': WordsInvariants.start(),
}
