#! /bin/bash

VERSION=$1

for TS in `ls -v -1 sbt-*/src/sbt-test/sbt-*/*/src/test/resources/*.ts`
do
  echo -n "$TS ..."

  sed -e "s|// Generated by ScalaTS [0-9A-Za-z\\.-]*|// Generated by ScalaTS $VERSION|" < \
    "$TS" > "$TS.tmp"
  mv "$TS.tmp" "$TS"

  echo " OK"
done
