// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export const AlabamaInhabitant = "AL";

export type Alabama = typeof AlabamaInhabitant;

export function isAlabama(v: any): v is Alabama {
  return AlabamaInhabitant == v;
}
