// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export const AlaskaInhabitant = "AK";

export type Alaska = typeof AlaskaInhabitant;

export function isAlaska(v: any): v is Alaska {
  return AlaskaInhabitant == v;
}
