// Generated by ScalaTS 0.6.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsAlaska = exports;

export const AlaskaInhabitant = "AK";

export type Alaska = typeof AlaskaInhabitant;

export function isAlaska(v: any): v is Alaska {
  return AlaskaInhabitant == v;
}
