// Generated by ScalaTS 0.5.12-SNAPSHOT: https://scala-ts.github.io/scala-ts/

export const ByeInhabitant = 'Bye';

export type Bye = typeof ByeInhabitant;

export function isBye(v: any): v is Bye {
  return ByeInhabitant == v;
}
