// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsBye = exports;

export const ByeInhabitant = 'Bye';

export type Bye = typeof ByeInhabitant;

export function isBye(v: any): v is Bye {
  return ByeInhabitant == v;
}

export type ByeSingleton = Bye;
