// Generated by ScalaTS 0.5.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import type { Whatever } from './Whatever';
import type { Hi } from './Hi';
import type { Bye } from './Bye';
import type { Hello } from './Hello';
import type { GoodBye } from './GoodBye';

export type Greeting = Bye | GoodBye | Hello | Hi | Whatever;
