// Generated by ScalaTS 0.8.1: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsGreeting = exports;

import * as nsBye from './Bye';
import * as nsGoodBye from './GoodBye';
import * as nsHello from './Hello';
import * as nsHi from './Hi';
import * as nsWhatever from './Whatever';
import type { Whatever } from './Whatever';

export const dependencyModules = [
  nsBye,
  nsGoodBye,
  nsHello,
  nsHi,
  nsWhatever,
];

export type GreetingUnion = nsBye.Bye | nsGoodBye.GoodBye | nsHello.Hello | nsHi.Hi | Whatever;

export const GreetingUnion = {
  Bye: nsBye.ByeInhabitant, 
  GoodBye: nsGoodBye.GoodByeInhabitant, 
  Hello: nsHello.HelloInhabitant, 
  Hi: nsHi.HiInhabitant
} as const;

export function isGreetingUnion(v: any): v is GreetingUnion {
  return (
    nsBye.isBye(v) ||
    nsGoodBye.isGoodBye(v) ||
    nsHello.isHello(v) ||
    nsHi.isHi(v) ||
    nsWhatever.isWhatever(v)
  );
}

export const GreetingSingletonInhabitant = 'GreetingSingleton';

export type GreetingSingleton = typeof GreetingSingletonInhabitant;

export function isGreetingSingleton(v: any): v is GreetingSingleton {
  return GreetingSingletonInhabitant == v;
}

class GreetingSingletonValuesClass {
  public readonly Hello: nsHello.HelloSingleton = nsHello.HelloInhabitant;
  public readonly GoodBye: nsGoodBye.GoodByeSingleton = nsGoodBye.GoodByeInhabitant;
  public readonly Hi: nsHi.HiSingleton = nsHi.HiInhabitant;
  public readonly Bye: nsBye.ByeSingleton = nsBye.ByeInhabitant;
}

export const GreetingSingletonValues = new GreetingSingletonValuesClass();

export const GreetingInhabitant = GreetingSingletonInhabitant;

export type Greeting = GreetingUnion;

export function isGreeting(v: any): v is Greeting {
  return (
    isGreetingUnion(v)
  );
}