// Generated by ScalaTS 0.7.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsHello = exports;

export const HelloInhabitant = 'Hello';

export type Hello = typeof HelloInhabitant;

export function isHello(v: any): v is Hello {
  return HelloInhabitant == v;
}

export type HelloSingleton = Hello;
