// Generated by ScalaTS 0.5.10-SNAPSHOT: https://scala-ts.github.io/scala-ts/

export const HiInhabitant = 'Hi';

export type Hi = typeof HiInhabitant;

export function isHi(v: any): v is Hi {
  return HiInhabitant == v;
}
