// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsHi = exports;

export const HiInhabitant = 'Hi';

export type Hi = typeof HiInhabitant;

export function isHi(v: any): v is Hi {
  return HiInhabitant == v;
}

export type HiSingleton = Hi;
