// Generated by ScalaTS 0.5.12-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import * as nsAlabama from './Alabama';
import { Alabama, isAlabama } from './Alabama';
import * as nsAlaska from './Alaska';
import { Alaska, isAlaska } from './Alaska';

export type State = Alabama | Alaska;

export const State = {
  "AL": nsAlabama.AlabamaInhabitant, 
  "AK": nsAlaska.AlaskaInhabitant
} as const;

export function isState(v: any): v is State {
  return (
    isAlabama(v) ||
    isAlaska(v)
  );
}
