// Generated by ScalaTS 0.5.7-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Alabama, isAlabama } from './Alabama';
import { Alaska, isAlaska } from './Alaska';

export type State = Alabama | Alaska;

export function isState(v: any): v is State {
  return (
    isAlabama(v) ||
    isAlaska(v)
  );
}
