// Generated by ScalaTS 0.4.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Whatever } from './Whatever';
import { Hi } from './Hi';
import { Bye } from './Bye';
import { Hello } from './Hello';
import { GoodBye } from './GoodBye';

export type Greeting = Bye | GoodBye | Hello | Hi | Whatever;
