// Generated by ScalaTS 0.5.7-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Alabama
export const idtltAlabama = idtlt.literal("AL");

// Super-type declaration State is ignored
export const idtltDiscriminatedAlabama = idtltAlabama;

// Deriving TypeScript type from Alabama validator
export type Alabama = typeof idtltAlabama.T;
