// Generated by ScalaTS 0.5.4-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Alaska
export const idtltAlaska = idtlt.literal("AK");

// Super-type declaration State is ignored
export const idtltDiscriminatedAlaska = idtltAlaska;

// Deriving TypeScript type from Alaska validator
export type Alaska = typeof idtltAlaska.T;
