// Generated by ScalaTS 0.5.8-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import * as nsName from './Name';
import * as nsTransport from './Transport';

// Validator for InterfaceDeclaration Bar
export const idtltBar = idtlt.object({
  created: idtlt.isoDate,
  updated: idtlt.isoDate,
  transports: idtlt.array(nsTransport.idtltTransport),
  amount: idtlt.number.optional(),
  age: idtlt.number,
  aliases: idtlt.array(nsName.idtltName),
  name: nsName.idtltName,
});

// Deriving TypeScript type from Bar validator
export type Bar = typeof idtltBar.T;

export const idtltDiscriminatedBar = idtlt.intersection(
  idtltBar,
  idtlt.object({
    _type: idtlt.literal('Bar')
  })
);

// Deriving TypeScript type from idtltDiscriminatedBar validator
export type DiscriminatedBar = typeof idtltDiscriminatedBar.T;

export const discriminatedBar: (_: Bar) => DiscriminatedBar = (v: Bar) => ({ _type: 'Bar', ...v });

export function isBar(v: any): v is Bar {
  return (
    (v['created'] && (v['created'] instanceof Date)) &&
    (v['updated'] && (v['updated'] instanceof Date)) &&
    (Array.isArray(v['transports']) && v['transports'].every(elmt => elmt && nsTransport.isTransport(elmt))) &&
    (!v['amount'] || ((typeof v['amount']) === 'number')) &&
    ((typeof v['age']) === 'number') &&
    (Array.isArray(v['aliases']) && v['aliases'].every(elmt => elmt && nsName.isName(elmt))) &&
    (v['name'] && nsName.isName(v['name']))
  );
}
