// Generated by ScalaTS 0.5.5-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration BarNum
export const idtltBarNum = idtlt.literal('BarNum')

// Super-type declaration Feature is ignored
export const idtltDiscriminatedBarNum = idtltBarNum;

// Deriving TypeScript type from BarNum validator
export type BarNum = typeof idtltBarNum.T;
