// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';
export const _externalDependencyModules = [idtlt];

declare var exports: any;

export const nsConstants = exports;

import * as nsCategory from './Category';
import * as nsName from './Name';
import * as nsState from './State';

export const dependencyModules = [
  nsCategory,
  nsName,
  nsState,
];

export class Constants {
  public readonly code: number & 1 = 1;

  public readonly UnknownName: nsName.Name & "unknown" = nsName.Name("unknown");

  public readonly defaultName: nsName.Name & "default" = nsName.Name("default");

  public readonly list: ReadonlyArray<number> = [ this.code, 2 ];

  public readonly dict: Readonly<Map<string, ReadonlyArray<nsName.Name>>> = new Map([ ["specific", [ this.UnknownName, this.defaultName, nsName.Name("*") ]], ["invalid", [ nsName.Name("failed") ]] ]);

  public readonly excluded: ReadonlyArray<string> = [ "foo", "bar" ];

  public readonly filtered: ReadonlyArray<string> = [ ...this.excluded, ...[ "filtered" ]];

  public readonly names: ReadonlyArray<nsName.Name> = [ ...[ this.UnknownName, this.defaultName ], ...[ nsName.Name("test") ]];

  public readonly mapping: Readonly<Map<string, Readonly<Map<string, Readonly<Map<nsState.State, nsCategory.Category>>>>>> = new Map([ ["Foo", new Map([ ["Lorem", (() => { const __buf707341971: Map<nsState.State, nsCategory.Category> = new Map(); __buf707341971.set(nsState.State.Alabama, nsCategory.Category.Lorem); __buf707341971.set(nsState.State.Alaska, nsCategory.Category.Ipsum); return __buf707341971 })()] ])] ]);

  private static instance: Constants;

  private constructor() {}

  public static getInstance() {
    if (!Constants.instance) {
      Constants.instance = new Constants();
    }

    return Constants.instance;
  }
}

export const ConstantsInhabitant: Constants = Constants.getInstance();

export function isConstants(v: any): v is Constants {
  return (v instanceof Constants) && (v === ConstantsInhabitant);
}

export const idtltConstants =
  idtlt.unknown.and(_unknown => idtlt.Err(
    'Cannot validator instance for singleton Constants'));
