// Generated by ScalaTS 0.5.5-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration GoodBye
export const idtltGoodBye = idtlt.literal('GoodBye')

// Super-type declaration Greeting is ignored
export const idtltDiscriminatedGoodBye = idtltGoodBye;

// Deriving TypeScript type from GoodBye validator
export type GoodBye = typeof idtltGoodBye.T;
