// Generated by ScalaTS 0.5.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Hello
export const idtltHello = idtlt.literal('Hello')

// Super-type declaration Greeting is ignored
export const idtltDiscriminatedHello = idtltHello;

// Deriving TypeScript type from Hello validator
export type Hello = typeof idtltHello.T;
