// Generated by ScalaTS 0.5.6: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Hi
export const idtltHi = idtlt.literal('Hi')

// Super-type declaration Greeting is ignored
export const idtltDiscriminatedHi = idtltHi;

// Deriving TypeScript type from Hi validator
export type Hi = typeof idtltHi.T;
