// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';
export const _externalDependencyModules = [idtlt];

declare var exports: any;

export const nsIpsum = exports;

// Validator for SingletonDeclaration Ipsum
export const idtltIpsum = idtlt.literal('Ipsum')

// Super-type declaration Category is ignored
export const idtltDiscriminatedIpsum = idtltIpsum;

// Deriving TypeScript type from Ipsum validator
export type Ipsum = typeof idtltIpsum.T;

export const IpsumInhabitant: Ipsum = 'Ipsum';

export function isIpsum(v: any): v is Ipsum {
  return idtltIpsum.validate(v).ok;
}

export type IpsumSingleton = Ipsum;