// Generated by ScalaTS 0.5.6-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Validator for SingletonDeclaration Lorem
export const idtltLorem = idtlt.literal('Lorem')

// Super-type declaration Category is ignored
export const idtltDiscriminatedLorem = idtltLorem;

// Deriving TypeScript type from Lorem validator
export type Lorem = typeof idtltLorem.T;
