// Generated by ScalaTS 0.8.0: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';
export const _externalDependencyModules = [idtlt];

declare var exports: any;

export const nsLorem = exports;

// Validator for SingletonDeclaration Lorem
export const idtltLorem = idtlt.literal('Lorem')

// Super-type declaration Category is ignored
export const idtltDiscriminatedLorem = idtltLorem;

// Deriving TypeScript type from Lorem validator
export type Lorem = typeof idtltLorem.T;

export const LoremInhabitant: Lorem = 'Lorem';

export function isLorem(v: any): v is Lorem {
  return idtltLorem.validate(v).ok;
}

export type LoremSingleton = Lorem;