// Generated by ScalaTS 0.7.2-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';
export const _externalDependencyModules = [idtlt];

declare var exports: any;

export const nsName = exports;

// Validator for TaggedDeclaration Name
export type Name = string & { __tag: 'Name' };

export function Name<T extends string>(value: T): Name & T {
  return value as (Name & T);
}

export const idtltName = idtlt.string.tagged<Name>();

export function isName(v: any): v is Name {
  return idtltName.validate(v).ok;
}
