// Generated by ScalaTS 0.5.4-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

import * as nsNotSupportedClassAsTypeArgs from './NotSupportedClassAsTypeArgs';

// Validator for InterfaceDeclaration NotSupportedAsNotSupportedField
export const idtltNotSupportedAsNotSupportedField = idtlt.object({
  notSupportedClassAsTypeArgs: idtlt.unknown /* Unsupported 'NotSupportedClassAsTypeArgs'; Type parameters: idtlt.number */,
});

export const idtltDiscriminatedNotSupportedAsNotSupportedField = idtlt.intersection(
  idtltNotSupportedAsNotSupportedField,
  idtlt.object({
    '_type': idtlt.literal('NotSupportedAsNotSupportedField')
  })
);

// Deriving TypeScript type from NotSupportedAsNotSupportedField validator
export type NotSupportedAsNotSupportedField = typeof idtltNotSupportedAsNotSupportedField.T;
