// Generated by ScalaTS 0.8.1-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';
export const _externalDependencyModules = [idtlt];

declare var exports: any;

export const nsNotSupportedClassAsTypeArgs = exports;

// Not supported: InterfaceDeclaration 'NotSupportedClassAsTypeArgs'
// - type parameters: T

export function isNotSupportedClassAsTypeArgs(v: any): boolean {
  return v && false;
}
