// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Not supported: InterfaceDeclaration 'NotSupportedClassAsTypeArgs'
// - type parameters: T

export function isNotSupportedClassAsTypeArgs(v: any): boolean {
  return false;
}
