// Generated by ScalaTS 0.5.4-SNAPSHOT: https://scala-ts.github.io/scala-ts/
import * as idtlt from 'idonttrustlikethat';

// Not supported: InterfaceDeclaration 'NotSupportedClassAsTypeArgs'
// - type parameters: T
