// Generated by ScalaTS 0.8.0: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsBar = exports;

import * as nsFeature from './Feature';
import type { Feature } from './Feature';

export const dependencyModules = [
  nsFeature,
];

export class Bar implements Feature {
  private static instance: Bar;

  private constructor() {}

  public static getInstance() {
    if (!Bar.instance) {
      Bar.instance = new Bar();
    }

    return Bar.instance;
  }
}

export const BarInhabitant: Bar = Bar.getInstance();

export function isBar(v: any): v is Bar {
  return (v instanceof Bar) && (v === BarInhabitant);
}

export type BarSingleton = Bar;
