// Generated by ScalaTS 0.5.13-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsCategory = exports;

export interface Category {
}

export function isCategory(v: any): v is Category {
  return (
    v === {}
  );
}
