// Generated by ScalaTS 0.5.17: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsCategory = exports;

export interface Category {
}

export function isCategory(v: any): v is Category {
  return (
    typeof v === 'object' && Object.keys(v).length === 0
  );
}
