// Generated by ScalaTS 0.5.16-SNAPSHOT: https://scala-ts.github.io/scala-ts/

declare var exports: any;

export const nsFeature = exports;

export interface Feature {
}

export function isFeature(v: any): v is Feature {
  return (
    typeof v === 'object' && Object.keys(v).length === 0
  );
}
