// Generated by ScalaTS 0.5.9-SNAPSHOT: https://scala-ts.github.io/scala-ts/

import { Feature, isFeature } from './Feature';

export interface NamedFeature {
  name: string;
  feature: Feature;
}

export function isNamedFeature(v: any): v is NamedFeature {
  return (
    (v['feature'] && isFeature(v['feature'])) &&
    ((typeof v['name']) === 'string')
  );
}
